export const availActivities = [
  'AUTO TOURING',
  'BIKING',
  'BOATING',
  'CLIMBING',
  'HISTORIC & CULTURAL SITE',
  'CAMPING',
  'FISHING',
  'HIKING',
  'HORSEBACK RIDING',
  'HUNTING',
  'OFF HIGHWAY VEHICLE',
  'PICNICKING',
  'WINTER SPORTS',
  'RECREATIONAL VEHICLES',
  'VISITOR CENTER',
  'WATER SPORTS',
  'WILDLIFE VIEWING',
  'FISH HATCHERY',
  'WILDERNESS',
  'FIRE LOOKOUTS/CABINS OVERNIGHT',
  'FISH VIEWING SITE',
  'DAY USE AREA',
  'DOCUMENTARY SITE',
  'SWIMMING SITE',
  'PLAYGROUND PARK SPECIALIZED SPORT SITE',
  'OTHER RECREATION CONCESSION SITE',
  'OBSERVATION SITE',
  'HOTEL/LODGE/RESORT FS OWNED',
  'INFORMATION SITE',
  'RECREATION RESIDENCE',
  'SNOWPARK',
  'ENVIRONMENTAL EDUCATION',
  'PHOTOGRAPHY',
  'PADDLING',
  'SWIMMING',
  'DIVING',
  'SNORKELING',
  'HORSE CAMPING'
];

export const stateList = {
  AL: 'Alabama',
  AK: 'Alaska',
  AS: 'American Samoa',
  AZ: 'Arizona',
  AR: 'Arkansas',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DE: 'Delaware',
  DC: 'District Of Columbia',
  FM: 'Federated States Of Micronesia',
  FL: 'Florida',
  GA: 'Georgia',
  GU: 'Guam',
  HI: 'Hawaii',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  IA: 'Iowa',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  ME: 'Maine',
  MH: 'Marshall Islands',
  MD: 'Maryland',
  MA: 'Massachusetts',
  MI: 'Michigan',
  MN: 'Minnesota',
  MS: 'Mississippi',
  MO: 'Missouri',
  MT: 'Montana',
  NE: 'Nebraska',
  NV: 'Nevada',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NY: 'New York',
  NC: 'North Carolina',
  ND: 'North Dakota',
  MP: 'Northern Mariana Islands',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PW: 'Palau',
  PA: 'Pennsylvania',
  PR: 'Puerto Rico',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VT: 'Vermont',
  VI: 'Virgin Islands',
  VA: 'Virginia',
  WA: 'Washington',
  WV: 'West Virginia',
  WI: 'Wisconsin',
  WY: 'Wyoming'
};
